const data = {
    products:[
        {
            _id: '1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id: '2',
            name:'Puma Slim Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            price: 100,
            brand:'Puma',
            rating:3,
            numReviews:3,
            description:'high quality product',
        },
        {
            _id: '3',
            name:'Noopa Slim Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:230,
            brand:'Noopa',
            rating:4,
            numReviews:13,
            description:'high quality product',
        },
        {
            _id: '4',
            name:'Niwed Slim Cotton',
            category:'Trousers',
            image:'/images/p4.jpg',
            price:100,
            brand:'Niwed',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id: '5',
            name:'Puzekk Slim Cotton',
            category:'Trousers',
            image:'/images/p5.jpg',
            price:60,
            brand:'Puzekk',
            rating:2,
            numReviews:7,
            description:'high quality product',
        },
        {
            _id: '6',
            name:'Adidas fit pants',
            category:'Trousers',
            image:'/images/p6.jpg',
            price:123,
            brand:'Adidas',
            rating:6,
            numReviews:12,
            description:'high quality product',
        },
        
    ],
}

export default data;